import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ar";

const translations = {
  en: {
    dashboard: "Dashboard",
    terminal: "Terminal",
    editor: "Editor",
    files: "Files",
    ai_chat: "AI Chat",
    commands: "Commands",
    admin: "Admin Panel",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    login_title: "Welcome to SERVER HUB",
    login_subtitle: "Sign in to manage your server",
    username: "Username",
    password: "Password",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    invalid_credentials: "Invalid username or password",
    system_overview: "System Overview",
    live_monitoring: "Live monitoring and resource usage",
    cpu_usage: "CPU Usage",
    memory: "Memory",
    disk_space: "Disk Space",
    uptime: "Uptime",
    open_ports: "Open Ports",
    top_processes: "Top Processes",
    no_ports: "No open ports detected",
    no_processes: "No processes found",
    kill: "Kill",
    total: "total",
    cores: "Cores",
    load: "Load",
    of: "of",
    explorer: "Explorer",
    new_file: "New File",
    new_folder: "New Folder",
    upload: "Upload",
    search: "Search...",
    name: "Name",
    size: "Size",
    date: "Date",
    rename: "Rename",
    delete: "Delete",
    open: "Open",
    empty_folder: "Empty folder",
    no_results: "No results found",
    drop_to_upload: "Drop files to upload",
    select_file: "Select a file to open",
    save: "Save",
    new_terminal: "New Terminal",
    connected: "Connected",
    connecting: "Connecting",
    reconnecting: "Reconnecting...",
    offline: "Offline",
    clear: "Clear",
    restart: "Restart",
    ai_assistant: "AI Assistant",
    ai_subtitle: "Ask anything about server management, code, or Linux",
    analyze_file: "Analyze File",
    send: "Send",
    thinking: "Thinking...",
    ai_disclaimer: "AI may make mistakes. Verify important commands before running.",
    file_path: "File Path",
    question: "Question",
    analyze: "Analyze",
    analyzing: "Analyzing...",
    admin_panel: "Admin Panel",
    user_management: "User Management",
    create_user: "Create User",
    edit_user: "Edit User",
    delete_user: "Delete User",
    search_users: "Search users...",
    expires_in: "Expires in",
    days: "days",
    no_expiry: "No expiry",
    disabled: "Disabled",
    active: "Active",
    role: "Role",
    display_name: "Display Name",
    cancel: "Cancel",
    save_changes: "Save Changes",
    create: "Create",
    confirm_delete: "Confirm Delete",
    delete_confirm_msg: "Are you sure you want to delete this user?",
    last_login: "Last Login",
    never: "Never",
    settings_title: "Settings",
    telegram_settings: "Telegram Notifications",
    bot_token: "Bot Token",
    chat_id: "Chat ID / Admin ID",
    test_connection: "Test Connection",
    testing: "Testing...",
    enable_telegram: "Enable Telegram Notifications",
    notify_login: "Notify on login",
    notify_register: "Notify on user registration",
    notify_upload: "Notify on file upload",
    notify_error: "Notify on server error",
    language_settings: "Language",
    save_settings: "Save Settings",
    settings_saved: "Settings saved",
    test_success: "Test message sent successfully!",
    test_failed: "Test failed â€” check token and chat ID",
    profile_title: "Profile",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    upload_avatar: "Upload Avatar",
    account_info: "Account Info",
    subscription: "Subscription",
    expires: "Expires",
    unlimited: "Unlimited",
    save_profile: "Save Profile",
    profile_updated: "Profile updated successfully",
    passwords_dont_match: "Passwords don't match",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    confirm: "Confirm",
    close: "Close",
    back: "Back",
    server_hub: "SERVER HUB",
  },
  ar: {
    dashboard: "Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…",
    terminal: "Ø§Ù„Ø·Ø±ÙÙŠØ©",
    editor: "Ø§Ù„Ù…Ø­Ø±Ø±",
    files: "Ø§Ù„Ù…Ù„ÙØ§Øª",
    ai_chat: "Ø§Ù„Ù…Ø³Ø§Ø¹Ø¯ Ø§Ù„Ø°ÙƒÙŠ",
    commands: "Ø§Ù„Ø£ÙˆØ§Ù…Ø±",
    admin: "Ù„ÙˆØ­Ø© Ø§Ù„Ø¥Ø¯Ù…Ù†",
    settings: "Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª",
    profile: "Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ",
    logout: "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬",
    login: "ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„",
    login_title: "Ù…Ø±Ø­Ø¨Ø§Ù‹ Ø¨Ùƒ ÙÙŠ SERVER HUB",
    login_subtitle: "Ø³Ø¬Ù‘Ù„ Ø¯Ø®ÙˆÙ„Ùƒ Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø³ÙŠØ±ÙØ±",
    username: "Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…",
    password: "ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±",
    sign_in: "Ø¯Ø®ÙˆÙ„",
    signing_in: "Ø¬Ø§Ø±Ù Ø§Ù„Ø¯Ø®ÙˆÙ„...",
    invalid_credentials: "Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø£Ùˆ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± ØµØ­ÙŠØ­Ø©",
    system_overview: "Ù†Ø¸Ø±Ø© Ø¹Ø§Ù…Ø© Ø¹Ù„Ù‰ Ø§Ù„Ù†Ø¸Ø§Ù…",
    live_monitoring: "Ù…Ø±Ø§Ù‚Ø¨Ø© Ù…Ø¨Ø§Ø´Ø±Ø© Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø§Ù„Ù…ÙˆØ§Ø±Ø¯",
    cpu_usage: "Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø§Ù„Ù…Ø¹Ø§Ù„Ø¬",
    memory: "Ø§Ù„Ø°Ø§ÙƒØ±Ø©",
    disk_space: "Ù…Ø³Ø§Ø­Ø© Ø§Ù„Ù‚Ø±Øµ",
    uptime: "ÙˆÙ‚Øª Ø§Ù„ØªØ´ØºÙŠÙ„",
    open_ports: "Ø§Ù„Ù…Ù†Ø§ÙØ° Ø§Ù„Ù…ÙØªÙˆØ­Ø©",
    top_processes: "Ø£Ø¨Ø±Ø² Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª",
    no_ports: "Ù„Ø§ ØªÙˆØ¬Ø¯ Ù…Ù†Ø§ÙØ° Ù…ÙØªÙˆØ­Ø©",
    no_processes: "Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ù…Ù„ÙŠØ§Øª",
    kill: "Ø¥ÙŠÙ‚Ø§Ù",
    total: "Ø¥Ø¬Ù…Ø§Ù„ÙŠ",
    cores: "Ø£Ù†ÙˆÙŠØ©",
    load: "Ø§Ù„Ø­Ù…Ù„",
    of: "Ù…Ù†",
    explorer: "Ø§Ù„Ù…Ø³ØªØ¹Ø±Ø¶",
    new_file: "Ù…Ù„Ù Ø¬Ø¯ÙŠØ¯",
    new_folder: "Ù…Ø¬Ù„Ø¯ Ø¬Ø¯ÙŠØ¯",
    upload: "Ø±ÙØ¹ Ù…Ù„Ù",
    search: "Ø¨Ø­Ø«...",
    name: "Ø§Ù„Ø§Ø³Ù…",
    size: "Ø§Ù„Ø­Ø¬Ù…",
    date: "Ø§Ù„ØªØ§Ø±ÙŠØ®",
    rename: "Ø¥Ø¹Ø§Ø¯Ø© Ø§Ù„ØªØ³Ù…ÙŠØ©",
    delete: "Ø­Ø°Ù",
    open: "ÙØªØ­",
    empty_folder: "Ø§Ù„Ù…Ø¬Ù„Ø¯ ÙØ§Ø±Øº",
    no_results: "Ù„Ø§ ØªÙˆØ¬Ø¯ Ù†ØªØ§Ø¦Ø¬",
    drop_to_upload: "Ø£Ø³Ù‚Ø· Ø§Ù„Ù…Ù„ÙØ§Øª Ù„Ù„Ø±ÙØ¹",
    select_file: "Ø§Ø®ØªØ± Ù…Ù„ÙØ§Ù‹ Ù„Ù„ÙØªØ­",
    save: "Ø­ÙØ¸",
    new_terminal: "Ø·Ø±ÙÙŠØ© Ø¬Ø¯ÙŠØ¯Ø©",
    connected: "Ù…ØªØµÙ„",
    connecting: "Ø¬Ø§Ø±Ù Ø§Ù„Ø§ØªØµØ§Ù„",
    reconnecting: "Ø¥Ø¹Ø§Ø¯Ø© Ø§Ù„Ø§ØªØµØ§Ù„...",
    offline: "ØºÙŠØ± Ù…ØªØµÙ„",
    clear: "Ù…Ø³Ø­",
    restart: "Ø¥Ø¹Ø§Ø¯Ø© ØªØ´ØºÙŠÙ„",
    ai_assistant: "Ø§Ù„Ù…Ø³Ø§Ø¹Ø¯ Ø§Ù„Ø°ÙƒÙŠ",
    ai_subtitle: "Ø§Ø³Ø£Ù„ Ø¹Ù† Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø³ÙŠØ±ÙØ±Ø§Øª Ø£Ùˆ Ø§Ù„Ø¨Ø±Ù…Ø¬Ø© Ø£Ùˆ Ù„ÙŠÙ†ÙƒØ³",
    analyze_file: "ØªØ­Ù„ÙŠÙ„ Ù…Ù„Ù",
    send: "Ø¥Ø±Ø³Ø§Ù„",
    thinking: "Ø¬Ø§Ø±Ù Ø§Ù„ØªÙÙƒÙŠØ±...",
    ai_disclaimer: "Ù‚Ø¯ ÙŠÙØ®Ø·Ø¦ Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ. ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„Ø£ÙˆØ§Ù…Ø± Ø§Ù„Ù…Ù‡Ù…Ø© Ù‚Ø¨Ù„ ØªØ´ØºÙŠÙ„Ù‡Ø§.",
    file_path: "Ù…Ø³Ø§Ø± Ø§Ù„Ù…Ù„Ù",
    question: "Ø§Ù„Ø³Ø¤Ø§Ù„",
    analyze: "ØªØ­Ù„ÙŠÙ„",
    analyzing: "Ø¬Ø§Ø±Ù Ø§Ù„ØªØ­Ù„ÙŠÙ„...",
    admin_panel: "Ù„ÙˆØ­Ø© Ø§Ù„Ø¥Ø¯Ù…Ù†",
    user_management: "Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ†",
    create_user: "Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø³ØªØ®Ø¯Ù…",
    edit_user: "ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…",
    delete_user: "Ø­Ø°Ù Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…",
    search_users: "Ø¨Ø­Ø« Ø¹Ù† Ù…Ø³ØªØ®Ø¯Ù…...",
    expires_in: "ØªÙ†ØªÙ‡ÙŠ Ø®Ù„Ø§Ù„",
    days: "Ø£ÙŠØ§Ù…",
    no_expiry: "Ø¨Ù„Ø§ Ø§Ù†ØªÙ‡Ø§Ø¡",
    disabled: "Ù…Ø¹Ø·Ù‘Ù„",
    active: "Ù†Ø´Ø·",
    role: "Ø§Ù„Ø¯ÙˆØ±",
    display_name: "Ø§Ù„Ø§Ø³Ù… Ø§Ù„Ø¸Ø§Ù‡Ø±",
    cancel: "Ø¥Ù„ØºØ§Ø¡",
    save_changes: "Ø­ÙØ¸ Ø§Ù„ØªØºÙŠÙŠØ±Ø§Øª",
    create: "Ø¥Ù†Ø´Ø§Ø¡",
    confirm_delete: "ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø­Ø°Ù",
    delete_confirm_msg: "Ù‡Ù„ Ø£Ù†Øª Ù…ØªØ£ÙƒØ¯ Ù…Ù† Ø­Ø°Ù Ù‡Ø°Ø§ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ØŸ",
    last_login: "Ø¢Ø®Ø± Ø¯Ø®ÙˆÙ„",
    never: "Ù„Ù… ÙŠØ³Ø¬Ù‘Ù„ Ø¨Ø¹Ø¯",
    settings_title: "Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª",
    telegram_settings: "Ø¥Ø´Ø¹Ø§Ø±Ø§Øª ØªÙŠÙ„ÙŠØ¬Ø±Ø§Ù…",
    bot_token: "ØªÙˆÙƒÙ† Ø§Ù„Ø¨ÙˆØª",
    chat_id: "Ù…Ø¹Ø±Ù Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø© / Ø§Ù„Ø¥Ø¯Ù…Ù†",
    test_connection: "Ø§Ø®ØªØ¨Ø§Ø± Ø§Ù„Ø§ØªØµØ§Ù„",
    testing: "Ø¬Ø§Ø±Ù Ø§Ù„Ø§Ø®ØªØ¨Ø§Ø±...",
    enable_telegram: "ØªÙØ¹ÙŠÙ„ Ø¥Ø´Ø¹Ø§Ø±Ø§Øª ØªÙŠÙ„ÙŠØ¬Ø±Ø§Ù…",
    notify_login: "Ø¥Ø´Ø¹Ø§Ø± Ø¹Ù†Ø¯ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„",
    notify_register: "Ø¥Ø´Ø¹Ø§Ø± Ø¹Ù†Ø¯ Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨",
    notify_upload: "Ø¥Ø´Ø¹Ø§Ø± Ø¹Ù†Ø¯ Ø±ÙØ¹ Ù…Ù„Ù",
    notify_error: "Ø¥Ø´Ø¹Ø§Ø± Ø¹Ù†Ø¯ Ø­Ø¯ÙˆØ« Ø®Ø·Ø£",
    language_settings: "Ø§Ù„Ù„ØºØ©",
    save_settings: "Ø­ÙØ¸ Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª",
    settings_saved: "ØªÙ… Ø­ÙØ¸ Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª",
    test_success: "ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø±Ø³Ø§Ù„Ø© Ø§Ø®ØªØ¨Ø§Ø± Ø¨Ù†Ø¬Ø§Ø­!",
    test_failed: "ÙØ´Ù„ Ø§Ù„Ø§Ø®ØªØ¨Ø§Ø± â€” ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„ØªÙˆÙƒÙ† ÙˆÙ…Ø¹Ø±Ù Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø©",
    profile_title: "Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ",
    change_password: "ØªØºÙŠÙŠØ± ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±",
    current_password: "ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø§Ù„Ø­Ø§Ù„ÙŠØ©",
    new_password: "ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©",
    confirm_password: "ØªØ£ÙƒÙŠØ¯ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±",
    upload_avatar: "Ø±ÙØ¹ ØµÙˆØ±Ø© Ø´Ø®ØµÙŠØ©",
    account_info: "Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø­Ø³Ø§Ø¨",
    subscription: "Ø§Ù„Ø§Ø´ØªØ±Ø§Ùƒ",
    expires: "ÙŠÙ†ØªÙ‡ÙŠ ÙÙŠ",
    unlimited: "ØºÙŠØ± Ù…Ø­Ø¯ÙˆØ¯",
    save_profile: "Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ù",
    profile_updated: "ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ",
    passwords_dont_match: "ÙƒÙ„Ù…ØªØ§ Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± Ù…ØªØ·Ø§Ø¨Ù‚ØªÙŠÙ†",
    loading: "Ø¬Ø§Ø±Ù Ø§Ù„ØªØ­Ù…ÙŠÙ„...",
    error: "Ø®Ø·Ø£",
    success: "Ù†Ø¬Ø§Ø­",
    confirm: "ØªØ£ÙƒÙŠØ¯",
    close: "Ø¥ØºÙ„Ø§Ù‚",
    back: "Ø±Ø¬ÙˆØ¹",
    server_hub: "Ø³ÙŠØ±ÙØ± Ù‡Ø§Ø¨",
  },
} as const;

type TranslationKey = keyof typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LangContext = createContext<LangContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("sh_lang") as Lang) || "en";
  });

  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("sh_lang", l);
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, isRTL: lang === "ar" }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used inside LanguageProvider");
  return ctx;
}
